https://jysperm.me/2016/10/nodejs-error-handling/
# 异常问题
出现错误后程序崩溃退出
出现错误后 HTTP 请求无响应
出现错误后数据被修改了「一半」，出现不一致
出现错误后没有记录日志或重复记录
在日志中打印了错误但没有提供调用栈和上下文

# 异常分类
预期的异常：参数不合法、前提条件不满足
非预期的异常：JavaScript 引擎的运行时异常

# 调用栈问题
无法在异步代码中直接使用 try … catch 

# 异步流程控制机制
Node.js style callback
Promise（co、async/await）
EventEmitter（Stream）

# 异常传递到顶层调用栈
uncaughtException 事件可以捕捉到那些已经被抛出到最顶层调用栈的异常

# 传递异常
注意 Promise / callback chain 不要从中间断开
**** 只处理已知的、必须在这里处理的异常，其他异常继续向外抛出
不要轻易地丢弃一个异常
传递的过程中可以向 err 对象上添加属性，补充上下文

# 小结
在层次化的架构中，很多时候在当前的层级没有足够的信息去决定如何处理错误，因此我们需要使用异常来将错误沿着调用栈逆向抛出，直到某个层级有足够的信息来处理这个错误。
在异步的场景下我们应该使用 Promise 或相兼容的流程控制工具来模拟异常机制。
传递异常时可以回滚数据或向其补充上下文，但如非必要，需要继续向外抛出。
让所有无法被恢复的错误传递到程序的「边界」处，统一处理。

## Error Handling
# Synchronous Error
Try..catch
# Aysnchronous Error
Promise / EnventEmitter
# uncaught exception
domain + cluster
//using domain, avoid: 1. uncaught exception in asynchronous. 2. try catch catching useless error
# using uncaught exception

https://www.joyent.com/node-js/production/design/errors


